version: '3'

services:
  api:
    image: ghcr.io/identicum/opa-demoapi-spring:latest
    restart: always
    ports:
      - 8081:8081
  opa:
    image: openpolicyagent/opa:latest
    restart: always
    ports:
      - 8181:8181
    volumes:
      - ./demoapi.rego:/demoapi.rego
    command:
    - "run"
    - "--server"
    - "--watch"
    - "--log-level=debug"
    - "/demoapi.rego"
  idp:
    image: quay.io/keycloak/keycloak:19.0.3-legacy
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - ./keycloak/startup-scripts/:/opt/jboss/startup-scripts/
      - ./keycloak/custom-scripts/:/opt/jboss/custom-scripts/
      - ./keycloak/objects/:/opt/jboss/keycloak/objects/
    ports:
      - 8080:8080
  spa:
    image: ghcr.io/identicum/spa-demoapp-vue:latest
    restart: always
    volumes:
      - ./nginx/conf/server.conf:/usr/local/openresty/nginx/conf/server.conf
    environment:
      NGINX_RESOLVER: 127.0.0.11 valid=5s
      NGINX_LOG_LEVEL: debug
      OIDC_DISCOVERY: http://idp:8080/auth/realms/demorealm/.well-known/openid-configuration
      OIDC_CLIENT_ID: spa_client_id
      OIDC_CLIENT_SECRET: spa_client_secret
    ports:
      - 80:80